#+TITLE: np-l10n-glossary
#+DATE: Saturday, Aug 15 2015
#+STARTUP: content

Public glossary maintained by foss-np community.

* Disclaimer
  The information contained in here is an attempt to collect data for
  the translation glossary. Information provided doesn't claim to be
  complete, accurate or reliable.

  However, We have tried our best for correctness and completeness
  with our resources and capability. You will be at your own risk and
  liable for any direct, indirect or consequential damage cause by the
  use of this content.

* What is l10n/i18n/g11n

  *Localization* (l10n) is the process of translating and adapting a
  product or service to a particular language, culture, and geographic
  market.

  *Internationalization* (i18n) is the process of adapting application
  (i.e. code) to be localizable, e.g. ensuring that application can
  support local requirements such as writing system, address format,
  date and time format, etc.

  *Globalization* is the combination of internationalization and
  localzation, making any product or service global, with simultaneous
  release in relevant markets.

* About Language

  Nepali language (aka: Pahadiya ne:पाहडिया, Parbatiya ne:पर्वतिय, Khas
  Kura/Bhasa ne:खास कुरा/भाषा) is Indo-Aryan language developed from
  its roots of Sanskrit ne:संस्कृत and simplification over the time and
  getting influenced by Tibeto-Burman Languages.

  more information in [about.org]

* Contribution

** Format
   Separater is semicolon(;) since devnagari has similar colon(:)
   character <unicode>
