#+TITLE: np-l10n-glossary

Public glossary maintained by foss-np community.

* Introduction

  Nepali language (aka: Pahadiya, Parbatiya, Khaskura) is Indo-Aryan
  language developed from its roots of Sanskrit and simplification
  over the time and getting influenced by Tibeto-Burman Languages.

  Spoken Area:
  - Nepal: Official language, lingua franca
  - India: North-east, Sikkim, Darjeeling
  - Bhutan
  - Myanmar

  Script:
  - Devanagari

  ISO Codes:
  - ISO 639-1 ne
  - ISO 639-2 nep
  - ISO 639-3 nep

  NEPALI OR NEPALESE

* What is l10n/i18n/g11n

  *Localization* (l10n) is the process of translating and adapting a
  product or service to a particular language, culture, and geographic
  market.

  *Internationalization* (i18n) is the process of adapting application
  (i.e. code) to be localizable, e.g. ensuring that application can
  support local requirements such as writing system, address format,
  date and time format, etc.

  *Globalization* is the combination of internationalization and
  localzation, making any product or service global, with simultaneous
  release in relevant markets.

* About Language

** Character Set

   We use Devanagari Scripts similar to that of Hindi, Marathi and
   Sanskrit, but there are some variations as follows :

   - Nepali writing does not use nukta or Nuqta  the under dot(.)
   - Nepali writing system uses ZWJ and ZWNJ for example to produce
     pareli-ra पर्‌यो , गर्‌यो  , भर्‌याङ , र्‌याल
   - Nepali writing system explicitly use vocalic rr and vocalic l,ll
     sound except ऋ ।

** Currency

   Nepali Rupees

   Rs.

** Gender
   There are three genders in Nepali

   - Feminine
   - Masculine
   - Neuter

   Most of the time Masculine nouns end at (a) or (aa) sound and
   feminine nouns end at (i) or (ii) you can rely on that up to some
   extent but relying on that only is a problematic concept.

   eg.
   पाठो/पाठी
   केटो/केटी
   बाख्रो/बाख्री
   राँगो/भैँसी
   मत्ता/ढोइ
   पुरुष/महिला
   हिरो/हिरोनी


** Metric Unit

   | English    | Nepali {short}    |
   |------------+-------------------|
   | millimeter | मिलीमिटर {ml}     |
   | centimeter | सेन्टी मिटर {सेमी}   |
   | meter      | मिटर {मि}         |
   |------------+-------------------|
   | Inches     | इन्च {इन्च}         |
   | Feet, ft   | फिट {फिट}         |
   | Inch       | इन्च {इन्च}         |
   |------------+-------------------|
   | degrees    | डिग्री {डिग्री}     |
   |------------+-------------------|
   | kilobyte   | किलोबाइट {केबी/KB} |
   | megabyte   | मेगाबाइट {मेबी/MB}  |
   |------------+-------------------|
   | kilogram   | किलोग्राम {केजी}    |
   |------------+-------------------|
   | liter      | लिटर {लि}         |




* Format
  Separater is semicolon(;) since nepali has the : character.

* Transliteration

  ह्रस्व मात्रा (vowel modifiers) is should be used.

  For example,
  #+BEGIN_EXAMPLE
  screen ; स्क्रिन
  stream ; स्ट्रिम
  beta   ; बिटा
  #+END_EXAMPLE

  Similarly, where there is “sh”, श should be used.

  For example,
  #+BEGIN_EXAMPLE
  spreadsheet ; स्प्रेडशिट
  stylesheet  ; स्टायलशिट
  shortcut    ; शर्टकट
  shell       ; शेल
  #+END_EXAMPLE


* Common rules

  isolated verbs like गरी, भनी should have दीर्घ इकार endings.

** Acronyms
   Acronyms should either be transliterated or left in English
   depending on general convention and usage. It is usually acceptable
   to not translate the acronym.  e.g. UNICEF is localized as युनिसेफ.

** Abbreviations
   Sometimes it may be necessary to use the abbreviated form of a
   noun, for example, Dec in place of December. You might need to
   abbreviate some words in the UI (mainly buttons or options names)
   due to lack of space. There could be two main ways for
   abbreviation, by taking the first letter of each word (for example
   USA), or by taking first few characters of a long word (for
   example, Sun for Sunday).
